/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOneSignalAPIClient/model/ApiKeyTokensListResponse.h"

namespace com {
namespace onesignal {
namespace client {
namespace model {



ApiKeyTokensListResponse::ApiKeyTokensListResponse()
{
    m_TokensIsSet = false;
}

ApiKeyTokensListResponse::~ApiKeyTokensListResponse()
{
}

void ApiKeyTokensListResponse::validate()
{
    // TODO: implement validation
}

web::json::value ApiKeyTokensListResponse::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_TokensIsSet)
    {
        val[utility::conversions::to_string_t(U("tokens"))] = ModelBase::toJson(m_Tokens);
    }

    return val;
}

bool ApiKeyTokensListResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("tokens"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("tokens")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<ApiKeyToken>> refVal_setTokens;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTokens);
            setTokens(refVal_setTokens);
        }
    }
    return ok;
}

void ApiKeyTokensListResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_TokensIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("tokens")), m_Tokens));
    }
}

bool ApiKeyTokensListResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("tokens"))))
    {
        std::vector<std::shared_ptr<ApiKeyToken>> refVal_setTokens;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("tokens"))), refVal_setTokens );
        setTokens(refVal_setTokens);
    }
    return ok;
}

std::vector<std::shared_ptr<ApiKeyToken>>& ApiKeyTokensListResponse::getTokens()
{
    return m_Tokens;
}

void ApiKeyTokensListResponse::setTokens(const std::vector<std::shared_ptr<ApiKeyToken>>& value)
{
    m_Tokens = value;
    m_TokensIsSet = true;
}

bool ApiKeyTokensListResponse::tokensIsSet() const
{
    return m_TokensIsSet;
}

void ApiKeyTokensListResponse::unsetTokens()
{
    m_TokensIsSet = false;
}
}
}
}
}


