/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOneSignalAPIClient/model/CopyTemplateRequest.h"

namespace com {
namespace onesignal {
namespace client {
namespace model {



CopyTemplateRequest::CopyTemplateRequest()
{
    m_Target_app_id = utility::conversions::to_string_t("");
    m_Target_app_idIsSet = false;
}

CopyTemplateRequest::~CopyTemplateRequest()
{
}

void CopyTemplateRequest::validate()
{
    // TODO: implement validation
}

web::json::value CopyTemplateRequest::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_Target_app_idIsSet)
    {
        val[utility::conversions::to_string_t(U("target_app_id"))] = ModelBase::toJson(m_Target_app_id);
    }

    return val;
}

bool CopyTemplateRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("target_app_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("target_app_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTargetAppId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTargetAppId);
            setTargetAppId(refVal_setTargetAppId);
        }
    }
    return ok;
}

void CopyTemplateRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_Target_app_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("target_app_id")), m_Target_app_id));
    }
}

bool CopyTemplateRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("target_app_id"))))
    {
        utility::string_t refVal_setTargetAppId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("target_app_id"))), refVal_setTargetAppId );
        setTargetAppId(refVal_setTargetAppId);
    }
    return ok;
}

utility::string_t CopyTemplateRequest::getTargetAppId() const
{
    return m_Target_app_id;
}

void CopyTemplateRequest::setTargetAppId(const utility::string_t& value)
{
    m_Target_app_id = value;
    m_Target_app_idIsSet = true;
}

bool CopyTemplateRequest::targetAppIdIsSet() const
{
    return m_Target_app_idIsSet;
}

void CopyTemplateRequest::unsetTarget_app_id()
{
    m_Target_app_idIsSet = false;
}
}
}
}
}


