/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOneSignalAPIClient/model/CreateApiKeyRequest.h"

namespace com {
namespace onesignal {
namespace client {
namespace model {



CreateApiKeyRequest::CreateApiKeyRequest()
{
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Ip_allowlist_mode = utility::conversions::to_string_t("");
    m_Ip_allowlist_modeIsSet = false;
    m_Ip_allowlistIsSet = false;
}

CreateApiKeyRequest::~CreateApiKeyRequest()
{
}

void CreateApiKeyRequest::validate()
{
    // TODO: implement validation
}

web::json::value CreateApiKeyRequest::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t(U("name"))] = ModelBase::toJson(m_Name);
    }
    if(m_Ip_allowlist_modeIsSet)
    {
        val[utility::conversions::to_string_t(U("ip_allowlist_mode"))] = ModelBase::toJson(m_Ip_allowlist_mode);
    }
    if(m_Ip_allowlistIsSet)
    {
        val[utility::conversions::to_string_t(U("ip_allowlist"))] = ModelBase::toJson(m_Ip_allowlist);
    }

    return val;
}

bool CreateApiKeyRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("ip_allowlist_mode"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("ip_allowlist_mode")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setIpAllowlistMode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIpAllowlistMode);
            setIpAllowlistMode(refVal_setIpAllowlistMode);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("ip_allowlist"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("ip_allowlist")));
        if(!fieldValue.is_null())
        {
            std::vector<utility::string_t> refVal_setIpAllowlist;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIpAllowlist);
            setIpAllowlist(refVal_setIpAllowlist);
        }
    }
    return ok;
}

void CreateApiKeyRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("name")), m_Name));
    }
    if(m_Ip_allowlist_modeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("ip_allowlist_mode")), m_Ip_allowlist_mode));
    }
    if(m_Ip_allowlistIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("ip_allowlist")), m_Ip_allowlist));
    }
}

bool CreateApiKeyRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("name"))), refVal_setName );
        setName(refVal_setName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("ip_allowlist_mode"))))
    {
        utility::string_t refVal_setIpAllowlistMode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("ip_allowlist_mode"))), refVal_setIpAllowlistMode );
        setIpAllowlistMode(refVal_setIpAllowlistMode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("ip_allowlist"))))
    {
        std::vector<utility::string_t> refVal_setIpAllowlist;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("ip_allowlist"))), refVal_setIpAllowlist );
        setIpAllowlist(refVal_setIpAllowlist);
    }
    return ok;
}

utility::string_t CreateApiKeyRequest::getName() const
{
    return m_Name;
}

void CreateApiKeyRequest::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool CreateApiKeyRequest::nameIsSet() const
{
    return m_NameIsSet;
}

void CreateApiKeyRequest::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t CreateApiKeyRequest::getIpAllowlistMode() const
{
    return m_Ip_allowlist_mode;
}

void CreateApiKeyRequest::setIpAllowlistMode(const utility::string_t& value)
{
    m_Ip_allowlist_mode = value;
    m_Ip_allowlist_modeIsSet = true;
}

bool CreateApiKeyRequest::ipAllowlistModeIsSet() const
{
    return m_Ip_allowlist_modeIsSet;
}

void CreateApiKeyRequest::unsetIp_allowlist_mode()
{
    m_Ip_allowlist_modeIsSet = false;
}
std::vector<utility::string_t>& CreateApiKeyRequest::getIpAllowlist()
{
    return m_Ip_allowlist;
}

void CreateApiKeyRequest::setIpAllowlist(const std::vector<utility::string_t>& value)
{
    m_Ip_allowlist = value;
    m_Ip_allowlistIsSet = true;
}

bool CreateApiKeyRequest::ipAllowlistIsSet() const
{
    return m_Ip_allowlistIsSet;
}

void CreateApiKeyRequest::unsetIp_allowlist()
{
    m_Ip_allowlistIsSet = false;
}
}
}
}
}


