/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOneSignalAPIClient/model/CustomEventsRequest.h"

namespace com {
namespace onesignal {
namespace client {
namespace model {



CustomEventsRequest::CustomEventsRequest()
{
    m_EventsIsSet = false;
}

CustomEventsRequest::~CustomEventsRequest()
{
}

void CustomEventsRequest::validate()
{
    // TODO: implement validation
}

web::json::value CustomEventsRequest::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_EventsIsSet)
    {
        val[utility::conversions::to_string_t(U("events"))] = ModelBase::toJson(m_Events);
    }

    return val;
}

bool CustomEventsRequest::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("events"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("events")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<CustomEvent>> refVal_setEvents;
            ok &= ModelBase::fromJson(fieldValue, refVal_setEvents);
            setEvents(refVal_setEvents);
        }
    }
    return ok;
}

void CustomEventsRequest::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_EventsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("events")), m_Events));
    }
}

bool CustomEventsRequest::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("events"))))
    {
        std::vector<std::shared_ptr<CustomEvent>> refVal_setEvents;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("events"))), refVal_setEvents );
        setEvents(refVal_setEvents);
    }
    return ok;
}

std::vector<std::shared_ptr<CustomEvent>>& CustomEventsRequest::getEvents()
{
    return m_Events;
}

void CustomEventsRequest::setEvents(const std::vector<std::shared_ptr<CustomEvent>>& value)
{
    m_Events = value;
    m_EventsIsSet = true;
}

bool CustomEventsRequest::eventsIsSet() const
{
    return m_EventsIsSet;
}

void CustomEventsRequest::unsetEvents()
{
    m_EventsIsSet = false;
}
}
}
}
}


