/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.1.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOneSignalAPIClient/model/ExportSubscriptionsSuccessResponse.h"

namespace com {
namespace onesignal {
namespace client {
namespace model {



ExportSubscriptionsSuccessResponse::ExportSubscriptionsSuccessResponse()
{
    m_Csv_file_url = utility::conversions::to_string_t("");
    m_Csv_file_urlIsSet = false;
}

ExportSubscriptionsSuccessResponse::~ExportSubscriptionsSuccessResponse()
{
}

void ExportSubscriptionsSuccessResponse::validate()
{
    // TODO: implement validation
}

web::json::value ExportSubscriptionsSuccessResponse::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_Csv_file_urlIsSet)
    {
        val[utility::conversions::to_string_t(U("csv_file_url"))] = ModelBase::toJson(m_Csv_file_url);
    }

    return val;
}

bool ExportSubscriptionsSuccessResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("csv_file_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("csv_file_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCsvFileUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCsvFileUrl);
            setCsvFileUrl(refVal_setCsvFileUrl);
        }
    }
    return ok;
}

void ExportSubscriptionsSuccessResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_Csv_file_urlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("csv_file_url")), m_Csv_file_url));
    }
}

bool ExportSubscriptionsSuccessResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("csv_file_url"))))
    {
        utility::string_t refVal_setCsvFileUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("csv_file_url"))), refVal_setCsvFileUrl );
        setCsvFileUrl(refVal_setCsvFileUrl);
    }
    return ok;
}

utility::string_t ExportSubscriptionsSuccessResponse::getCsvFileUrl() const
{
    return m_Csv_file_url;
}

void ExportSubscriptionsSuccessResponse::setCsvFileUrl(const utility::string_t& value)
{
    m_Csv_file_url = value;
    m_Csv_file_urlIsSet = true;
}

bool ExportSubscriptionsSuccessResponse::csvFileUrlIsSet() const
{
    return m_Csv_file_urlIsSet;
}

void ExportSubscriptionsSuccessResponse::unsetCsv_file_url()
{
    m_Csv_file_urlIsSet = false;
}
}
}
}
}


