/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.0.1
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOneSignalAPIClient/model/FilterExpression.h"

namespace com {
namespace onesignal {
namespace client {
namespace model {



FilterExpression::FilterExpression()
{
    m_Field = utility::conversions::to_string_t("");
    m_FieldIsSet = false;
    m_Key = utility::conversions::to_string_t("");
    m_KeyIsSet = false;
    m_Value = utility::conversions::to_string_t("");
    m_ValueIsSet = false;
    m_Hours_ago = utility::conversions::to_string_t("");
    m_Hours_agoIsSet = false;
    m_Radius = 0.0;
    m_RadiusIsSet = false;
    m_Lat = 0.0;
    m_LatIsSet = false;
    m_long = 0.0;
    m_longIsSet = false;
    m_Relation = utility::conversions::to_string_t("");
    m_RelationIsSet = false;
    m_r_operator = utility::conversions::to_string_t("");
    m_r_operatorIsSet = false;
}

FilterExpression::~FilterExpression()
{
}

void FilterExpression::validate()
{
    // TODO: implement validation
}

web::json::value FilterExpression::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_FieldIsSet)
    {
        val[utility::conversions::to_string_t(U("field"))] = ModelBase::toJson(m_Field);
    }
    if(m_KeyIsSet)
    {
        val[utility::conversions::to_string_t(U("key"))] = ModelBase::toJson(m_Key);
    }
    if(m_ValueIsSet)
    {
        val[utility::conversions::to_string_t(U("value"))] = ModelBase::toJson(m_Value);
    }
    if(m_Hours_agoIsSet)
    {
        val[utility::conversions::to_string_t(U("hours_ago"))] = ModelBase::toJson(m_Hours_ago);
    }
    if(m_RadiusIsSet)
    {
        val[utility::conversions::to_string_t(U("radius"))] = ModelBase::toJson(m_Radius);
    }
    if(m_LatIsSet)
    {
        val[utility::conversions::to_string_t(U("lat"))] = ModelBase::toJson(m_Lat);
    }
    if(m_longIsSet)
    {
        val[utility::conversions::to_string_t(U("long"))] = ModelBase::toJson(m_long);
    }
    if(m_RelationIsSet)
    {
        val[utility::conversions::to_string_t(U("relation"))] = ModelBase::toJson(m_Relation);
    }
    if(m_r_operatorIsSet)
    {
        val[utility::conversions::to_string_t(U("operator"))] = ModelBase::toJson(m_r_operator);
    }

    return val;
}

bool FilterExpression::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("field"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("field")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setField;
            ok &= ModelBase::fromJson(fieldValue, refVal_setField);
            setField(refVal_setField);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("key"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("key")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setKey;
            ok &= ModelBase::fromJson(fieldValue, refVal_setKey);
            setKey(refVal_setKey);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("value"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("value")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setValue;
            ok &= ModelBase::fromJson(fieldValue, refVal_setValue);
            setValue(refVal_setValue);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("hours_ago"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("hours_ago")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setHoursAgo;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHoursAgo);
            setHoursAgo(refVal_setHoursAgo);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("radius"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("radius")));
        if(!fieldValue.is_null())
        {
            double refVal_setRadius;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRadius);
            setRadius(refVal_setRadius);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("lat"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("lat")));
        if(!fieldValue.is_null())
        {
            double refVal_setLat;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLat);
            setLat(refVal_setLat);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("long"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("long")));
        if(!fieldValue.is_null())
        {
            double refVal_setLong;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLong);
            setLong(refVal_setLong);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("relation"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("relation")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setRelation;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRelation);
            setRelation(refVal_setRelation);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("operator"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("operator")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setROperator;
            ok &= ModelBase::fromJson(fieldValue, refVal_setROperator);
            setROperator(refVal_setROperator);
        }
    }
    return ok;
}

void FilterExpression::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_FieldIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("field")), m_Field));
    }
    if(m_KeyIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("key")), m_Key));
    }
    if(m_ValueIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("value")), m_Value));
    }
    if(m_Hours_agoIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("hours_ago")), m_Hours_ago));
    }
    if(m_RadiusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("radius")), m_Radius));
    }
    if(m_LatIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("lat")), m_Lat));
    }
    if(m_longIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("long")), m_long));
    }
    if(m_RelationIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("relation")), m_Relation));
    }
    if(m_r_operatorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("operator")), m_r_operator));
    }
}

bool FilterExpression::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("field"))))
    {
        utility::string_t refVal_setField;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("field"))), refVal_setField );
        setField(refVal_setField);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("key"))))
    {
        utility::string_t refVal_setKey;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("key"))), refVal_setKey );
        setKey(refVal_setKey);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("value"))))
    {
        utility::string_t refVal_setValue;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("value"))), refVal_setValue );
        setValue(refVal_setValue);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("hours_ago"))))
    {
        utility::string_t refVal_setHoursAgo;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("hours_ago"))), refVal_setHoursAgo );
        setHoursAgo(refVal_setHoursAgo);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("radius"))))
    {
        double refVal_setRadius;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("radius"))), refVal_setRadius );
        setRadius(refVal_setRadius);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("lat"))))
    {
        double refVal_setLat;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("lat"))), refVal_setLat );
        setLat(refVal_setLat);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("long"))))
    {
        double refVal_setLong;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("long"))), refVal_setLong );
        setLong(refVal_setLong);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("relation"))))
    {
        utility::string_t refVal_setRelation;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("relation"))), refVal_setRelation );
        setRelation(refVal_setRelation);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("operator"))))
    {
        utility::string_t refVal_setROperator;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("operator"))), refVal_setROperator );
        setROperator(refVal_setROperator);
    }
    return ok;
}

utility::string_t FilterExpression::getField() const
{
    return m_Field;
}

void FilterExpression::setField(const utility::string_t& value)
{
    m_Field = value;
    m_FieldIsSet = true;
}

bool FilterExpression::fieldIsSet() const
{
    return m_FieldIsSet;
}

void FilterExpression::unsetField()
{
    m_FieldIsSet = false;
}
utility::string_t FilterExpression::getKey() const
{
    return m_Key;
}

void FilterExpression::setKey(const utility::string_t& value)
{
    m_Key = value;
    m_KeyIsSet = true;
}

bool FilterExpression::keyIsSet() const
{
    return m_KeyIsSet;
}

void FilterExpression::unsetKey()
{
    m_KeyIsSet = false;
}
utility::string_t FilterExpression::getValue() const
{
    return m_Value;
}

void FilterExpression::setValue(const utility::string_t& value)
{
    m_Value = value;
    m_ValueIsSet = true;
}

bool FilterExpression::valueIsSet() const
{
    return m_ValueIsSet;
}

void FilterExpression::unsetValue()
{
    m_ValueIsSet = false;
}
utility::string_t FilterExpression::getHoursAgo() const
{
    return m_Hours_ago;
}

void FilterExpression::setHoursAgo(const utility::string_t& value)
{
    m_Hours_ago = value;
    m_Hours_agoIsSet = true;
}

bool FilterExpression::hoursAgoIsSet() const
{
    return m_Hours_agoIsSet;
}

void FilterExpression::unsetHours_ago()
{
    m_Hours_agoIsSet = false;
}
double FilterExpression::getRadius() const
{
    return m_Radius;
}

void FilterExpression::setRadius(double value)
{
    m_Radius = value;
    m_RadiusIsSet = true;
}

bool FilterExpression::radiusIsSet() const
{
    return m_RadiusIsSet;
}

void FilterExpression::unsetRadius()
{
    m_RadiusIsSet = false;
}
double FilterExpression::getLat() const
{
    return m_Lat;
}

void FilterExpression::setLat(double value)
{
    m_Lat = value;
    m_LatIsSet = true;
}

bool FilterExpression::latIsSet() const
{
    return m_LatIsSet;
}

void FilterExpression::unsetLat()
{
    m_LatIsSet = false;
}
double FilterExpression::getLong() const
{
    return m_long;
}

void FilterExpression::setLong(double value)
{
    m_long = value;
    m_longIsSet = true;
}

bool FilterExpression::r_longIsSet() const
{
    return m_longIsSet;
}

void FilterExpression::unsetlong()
{
    m_longIsSet = false;
}
utility::string_t FilterExpression::getRelation() const
{
    return m_Relation;
}

void FilterExpression::setRelation(const utility::string_t& value)
{
    m_Relation = value;
    m_RelationIsSet = true;
}

bool FilterExpression::relationIsSet() const
{
    return m_RelationIsSet;
}

void FilterExpression::unsetRelation()
{
    m_RelationIsSet = false;
}
utility::string_t FilterExpression::getROperator() const
{
    return m_r_operator;
}

void FilterExpression::setROperator(const utility::string_t& value)
{
    m_r_operator = value;
    m_r_operatorIsSet = true;
}

bool FilterExpression::rOperatorIsSet() const
{
    return m_r_operatorIsSet;
}

void FilterExpression::unsetr_operator()
{
    m_r_operatorIsSet = false;
}
}
}
}
}


