/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.2.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOneSignalAPIClient/model/GenericError.h"

namespace com {
namespace onesignal {
namespace client {
namespace model {



GenericError::GenericError()
{
    m_ErrorsIsSet = false;
    m_Success = false;
    m_SuccessIsSet = false;
    m_ReferenceIsSet = false;
}

GenericError::~GenericError()
{
}

void GenericError::validate()
{
    // TODO: implement validation
}

web::json::value GenericError::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_ErrorsIsSet)
    {
        val[utility::conversions::to_string_t(U("errors"))] = ModelBase::toJson(m_Errors);
    }
    if(m_SuccessIsSet)
    {
        val[utility::conversions::to_string_t(U("success"))] = ModelBase::toJson(m_Success);
    }
    if(m_ReferenceIsSet)
    {
        val[utility::conversions::to_string_t(U("reference"))] = ModelBase::toJson(m_Reference);
    }

    return val;
}

bool GenericError::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("errors"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("errors")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AnyType> refVal_setErrors;
            ok &= ModelBase::fromJson(fieldValue, refVal_setErrors);
            setErrors(refVal_setErrors);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("success"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("success")));
        if(!fieldValue.is_null())
        {
            bool refVal_setSuccess;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSuccess);
            setSuccess(refVal_setSuccess);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("reference"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("reference")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<AnyType> refVal_setReference;
            ok &= ModelBase::fromJson(fieldValue, refVal_setReference);
            setReference(refVal_setReference);
        }
    }
    return ok;
}

void GenericError::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_ErrorsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("errors")), m_Errors));
    }
    if(m_SuccessIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("success")), m_Success));
    }
    if(m_ReferenceIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("reference")), m_Reference));
    }
}

bool GenericError::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("errors"))))
    {
        std::shared_ptr<AnyType> refVal_setErrors;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("errors"))), refVal_setErrors );
        setErrors(refVal_setErrors);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("success"))))
    {
        bool refVal_setSuccess;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("success"))), refVal_setSuccess );
        setSuccess(refVal_setSuccess);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("reference"))))
    {
        std::shared_ptr<AnyType> refVal_setReference;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("reference"))), refVal_setReference );
        setReference(refVal_setReference);
    }
    return ok;
}

std::shared_ptr<AnyType> GenericError::getErrors() const
{
    return m_Errors;
}

void GenericError::setErrors(const std::shared_ptr<AnyType>& value)
{
    m_Errors = value;
    m_ErrorsIsSet = true;
}

bool GenericError::errorsIsSet() const
{
    return m_ErrorsIsSet;
}

void GenericError::unsetErrors()
{
    m_ErrorsIsSet = false;
}
bool GenericError::isSuccess() const
{
    return m_Success;
}

void GenericError::setSuccess(bool value)
{
    m_Success = value;
    m_SuccessIsSet = true;
}

bool GenericError::successIsSet() const
{
    return m_SuccessIsSet;
}

void GenericError::unsetSuccess()
{
    m_SuccessIsSet = false;
}
std::shared_ptr<AnyType> GenericError::getReference() const
{
    return m_Reference;
}

void GenericError::setReference(const std::shared_ptr<AnyType>& value)
{
    m_Reference = value;
    m_ReferenceIsSet = true;
}

bool GenericError::referenceIsSet() const
{
    return m_ReferenceIsSet;
}

void GenericError::unsetReference()
{
    m_ReferenceIsSet = false;
}
}
}
}
}


