/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOneSignalAPIClient/model/StartLiveActivitySuccessResponse.h"

namespace com {
namespace onesignal {
namespace client {
namespace model {



StartLiveActivitySuccessResponse::StartLiveActivitySuccessResponse()
{
    m_Notification_id = utility::conversions::to_string_t("");
    m_Notification_idIsSet = false;
}

StartLiveActivitySuccessResponse::~StartLiveActivitySuccessResponse()
{
}

void StartLiveActivitySuccessResponse::validate()
{
    // TODO: implement validation
}

web::json::value StartLiveActivitySuccessResponse::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_Notification_idIsSet)
    {
        val[utility::conversions::to_string_t(U("notification_id"))] = ModelBase::toJson(m_Notification_id);
    }

    return val;
}

bool StartLiveActivitySuccessResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("notification_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("notification_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setNotificationId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNotificationId);
            setNotificationId(refVal_setNotificationId);
        }
    }
    return ok;
}

void StartLiveActivitySuccessResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_Notification_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("notification_id")), m_Notification_id));
    }
}

bool StartLiveActivitySuccessResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("notification_id"))))
    {
        utility::string_t refVal_setNotificationId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("notification_id"))), refVal_setNotificationId );
        setNotificationId(refVal_setNotificationId);
    }
    return ok;
}

utility::string_t StartLiveActivitySuccessResponse::getNotificationId() const
{
    return m_Notification_id;
}

void StartLiveActivitySuccessResponse::setNotificationId(const utility::string_t& value)
{
    m_Notification_id = value;
    m_Notification_idIsSet = true;
}

bool StartLiveActivitySuccessResponse::notificationIdIsSet() const
{
    return m_Notification_idIsSet;
}

void StartLiveActivitySuccessResponse::unsetNotification_id()
{
    m_Notification_idIsSet = false;
}
}
}
}
}


