/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.2.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppRestOneSignalAPIClient/model/SubscriptionBody.h"

namespace com {
namespace onesignal {
namespace client {
namespace model {



SubscriptionBody::SubscriptionBody()
{
    m_SubscriptionIsSet = false;
}

SubscriptionBody::~SubscriptionBody()
{
}

void SubscriptionBody::validate()
{
    // TODO: implement validation
}

web::json::value SubscriptionBody::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_SubscriptionIsSet)
    {
        val[utility::conversions::to_string_t(U("subscription"))] = ModelBase::toJson(m_Subscription);
    }

    return val;
}

bool SubscriptionBody::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("subscription"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("subscription")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Subscription> refVal_setSubscription;
            ok &= ModelBase::fromJson(fieldValue, refVal_setSubscription);
            setSubscription(refVal_setSubscription);
        }
    }
    return ok;
}

void SubscriptionBody::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_SubscriptionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("subscription")), m_Subscription));
    }
}

bool SubscriptionBody::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("subscription"))))
    {
        std::shared_ptr<Subscription> refVal_setSubscription;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("subscription"))), refVal_setSubscription );
        setSubscription(refVal_setSubscription);
    }
    return ok;
}

std::shared_ptr<Subscription> SubscriptionBody::getSubscription() const
{
    return m_Subscription;
}

void SubscriptionBody::setSubscription(const std::shared_ptr<Subscription>& value)
{
    m_Subscription = value;
    m_SubscriptionIsSet = true;
}

bool SubscriptionBody::subscriptionIsSet() const
{
    return m_SubscriptionIsSet;
}

void SubscriptionBody::unsetSubscription()
{
    m_SubscriptionIsSet = false;
}
}
}
}
}


