/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ApiKeyTokensListResponse.h
 *
 * 
 */

#ifndef COM_ONESIGNAL_CLIENT_MODEL_ApiKeyTokensListResponse_H_
#define COM_ONESIGNAL_CLIENT_MODEL_ApiKeyTokensListResponse_H_


#include "CppRestOneSignalAPIClient/ModelBase.h"

#include "CppRestOneSignalAPIClient/model/ApiKeyToken.h"
#include <vector>

namespace com {
namespace onesignal {
namespace client {
namespace model {

class ApiKeyToken;

/// <summary>
/// 
/// </summary>
class  ApiKeyTokensListResponse
    : public ModelBase
{
public:
    ApiKeyTokensListResponse();
    virtual ~ApiKeyTokensListResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ApiKeyTokensListResponse members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<ApiKeyToken>>& getTokens();
    bool tokensIsSet() const;
    void unsetTokens();

    void setTokens(const std::vector<std::shared_ptr<ApiKeyToken>>& value);


protected:
    std::vector<std::shared_ptr<ApiKeyToken>> m_Tokens;
    bool m_TokensIsSet;
};


}
}
}
}

#endif /* COM_ONESIGNAL_CLIENT_MODEL_ApiKeyTokensListResponse_H_ */
