/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CopyTemplateRequest.h
 *
 * 
 */

#ifndef COM_ONESIGNAL_CLIENT_MODEL_CopyTemplateRequest_H_
#define COM_ONESIGNAL_CLIENT_MODEL_CopyTemplateRequest_H_


#include "CppRestOneSignalAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace onesignal {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  CopyTemplateRequest
    : public ModelBase
{
public:
    CopyTemplateRequest();
    virtual ~CopyTemplateRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CopyTemplateRequest members

    /// <summary>
    /// Destination OneSignal App ID in UUID v4 format.
    /// </summary>
    utility::string_t getTargetAppId() const;
    bool targetAppIdIsSet() const;
    void unsetTarget_app_id();

    void setTargetAppId(const utility::string_t& value);


protected:
    utility::string_t m_Target_app_id;
    bool m_Target_app_idIsSet;
};


}
}
}
}

#endif /* COM_ONESIGNAL_CLIENT_MODEL_CopyTemplateRequest_H_ */
