/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CreateApiKeyRequest.h
 *
 * 
 */

#ifndef COM_ONESIGNAL_CLIENT_MODEL_CreateApiKeyRequest_H_
#define COM_ONESIGNAL_CLIENT_MODEL_CreateApiKeyRequest_H_


#include "CppRestOneSignalAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <vector>

namespace com {
namespace onesignal {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  CreateApiKeyRequest
    : public ModelBase
{
public:
    CreateApiKeyRequest();
    virtual ~CreateApiKeyRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CreateApiKeyRequest members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();

    void setName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getIpAllowlistMode() const;
    bool ipAllowlistModeIsSet() const;
    void unsetIp_allowlist_mode();

    void setIpAllowlistMode(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getIpAllowlist();
    bool ipAllowlistIsSet() const;
    void unsetIp_allowlist();

    void setIpAllowlist(const std::vector<utility::string_t>& value);


protected:
    utility::string_t m_Name;
    bool m_NameIsSet;
    utility::string_t m_Ip_allowlist_mode;
    bool m_Ip_allowlist_modeIsSet;
    std::vector<utility::string_t> m_Ip_allowlist;
    bool m_Ip_allowlistIsSet;
};


}
}
}
}

#endif /* COM_ONESIGNAL_CLIENT_MODEL_CreateApiKeyRequest_H_ */
