/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CreateApiKeyResponse.h
 *
 * 
 */

#ifndef COM_ONESIGNAL_CLIENT_MODEL_CreateApiKeyResponse_H_
#define COM_ONESIGNAL_CLIENT_MODEL_CreateApiKeyResponse_H_


#include "CppRestOneSignalAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace onesignal {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  CreateApiKeyResponse
    : public ModelBase
{
public:
    CreateApiKeyResponse();
    virtual ~CreateApiKeyResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CreateApiKeyResponse members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getTokenId() const;
    bool tokenIdIsSet() const;
    void unsetToken_id();

    void setTokenId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getFormattedToken() const;
    bool formattedTokenIsSet() const;
    void unsetFormatted_token();

    void setFormattedToken(const utility::string_t& value);


protected:
    utility::string_t m_Token_id;
    bool m_Token_idIsSet;
    utility::string_t m_Formatted_token;
    bool m_Formatted_tokenIsSet;
};


}
}
}
}

#endif /* COM_ONESIGNAL_CLIENT_MODEL_CreateApiKeyResponse_H_ */
