/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CustomEventsRequest.h
 *
 * 
 */

#ifndef COM_ONESIGNAL_CLIENT_MODEL_CustomEventsRequest_H_
#define COM_ONESIGNAL_CLIENT_MODEL_CustomEventsRequest_H_


#include "CppRestOneSignalAPIClient/ModelBase.h"

#include "CppRestOneSignalAPIClient/model/CustomEvent.h"
#include <vector>

namespace com {
namespace onesignal {
namespace client {
namespace model {

class CustomEvent;

/// <summary>
/// 
/// </summary>
class  CustomEventsRequest
    : public ModelBase
{
public:
    CustomEventsRequest();
    virtual ~CustomEventsRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// CustomEventsRequest members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<CustomEvent>>& getEvents();
    bool eventsIsSet() const;
    void unsetEvents();

    void setEvents(const std::vector<std::shared_ptr<CustomEvent>>& value);


protected:
    std::vector<std::shared_ptr<CustomEvent>> m_Events;
    bool m_EventsIsSet;
};


}
}
}
}

#endif /* COM_ONESIGNAL_CLIENT_MODEL_CustomEventsRequest_H_ */
