/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.2.1
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * GenericError.h
 *
 * 
 */

#ifndef COM_ONESIGNAL_CLIENT_MODEL_GenericError_H_
#define COM_ONESIGNAL_CLIENT_MODEL_GenericError_H_


#include "CppRestOneSignalAPIClient/ModelBase.h"


namespace com {
namespace onesignal {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  GenericError
    : public ModelBase
{
public:
    GenericError();
    virtual ~GenericError();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// GenericError members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<AnyType> getErrors() const;
    bool errorsIsSet() const;
    void unsetErrors();

    void setErrors(const std::shared_ptr<AnyType>& value);

    /// <summary>
    /// 
    /// </summary>
    bool isSuccess() const;
    bool successIsSet() const;
    void unsetSuccess();

    void setSuccess(bool value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<AnyType> getReference() const;
    bool referenceIsSet() const;
    void unsetReference();

    void setReference(const std::shared_ptr<AnyType>& value);


protected:
    std::shared_ptr<AnyType> m_Errors;
    bool m_ErrorsIsSet;
    bool m_Success;
    bool m_SuccessIsSet;
    std::shared_ptr<AnyType> m_Reference;
    bool m_ReferenceIsSet;
};


}
}
}
}

#endif /* COM_ONESIGNAL_CLIENT_MODEL_GenericError_H_ */
