/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.2.1
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PropertiesBody.h
 *
 * 
 */

#ifndef COM_ONESIGNAL_CLIENT_MODEL_PropertiesBody_H_
#define COM_ONESIGNAL_CLIENT_MODEL_PropertiesBody_H_


#include "CppRestOneSignalAPIClient/ModelBase.h"

#include "CppRestOneSignalAPIClient/model/PropertiesObject.h"

namespace com {
namespace onesignal {
namespace client {
namespace model {

class PropertiesObject;

/// <summary>
/// 
/// </summary>
class  PropertiesBody
    : public ModelBase
{
public:
    PropertiesBody();
    virtual ~PropertiesBody();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// PropertiesBody members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<PropertiesObject> getProperties() const;
    bool propertiesIsSet() const;
    void unsetProperties();

    void setProperties(const std::shared_ptr<PropertiesObject>& value);


protected:
    std::shared_ptr<PropertiesObject> m_Properties;
    bool m_PropertiesIsSet;
};


}
}
}
}

#endif /* COM_ONESIGNAL_CLIENT_MODEL_PropertiesBody_H_ */
