/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * SubscriptionBody.h
 *
 * 
 */

#ifndef COM_ONESIGNAL_CLIENT_MODEL_SubscriptionBody_H_
#define COM_ONESIGNAL_CLIENT_MODEL_SubscriptionBody_H_


#include "CppRestOneSignalAPIClient/ModelBase.h"

#include "CppRestOneSignalAPIClient/model/Subscription.h"

namespace com {
namespace onesignal {
namespace client {
namespace model {

class Subscription;

/// <summary>
/// 
/// </summary>
class  SubscriptionBody
    : public ModelBase
{
public:
    SubscriptionBody();
    virtual ~SubscriptionBody();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SubscriptionBody members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Subscription> getSubscription() const;
    bool subscriptionIsSet() const;
    void unsetSubscription();

    void setSubscription(const std::shared_ptr<Subscription>& value);


protected:
    std::shared_ptr<Subscription> m_Subscription;
    bool m_SubscriptionIsSet;
};


}
}
}
}

#endif /* COM_ONESIGNAL_CLIENT_MODEL_SubscriptionBody_H_ */
