/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TemplateResource.h
 *
 * 
 */

#ifndef COM_ONESIGNAL_CLIENT_MODEL_TemplateResource_H_
#define COM_ONESIGNAL_CLIENT_MODEL_TemplateResource_H_


#include "CppRestOneSignalAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <map>
#include <vector>

namespace com {
namespace onesignal {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  TemplateResource
    : public ModelBase
{
public:
    TemplateResource();
    virtual ~TemplateResource();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// TemplateResource members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();

    void setId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();

    void setName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreated_at();

    void setCreatedAt(const utility::datetime& value);

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getUpdatedAt() const;
    bool updatedAtIsSet() const;
    void unsetUpdated_at();

    void setUpdatedAt(const utility::datetime& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getChannel() const;
    bool channelIsSet() const;
    void unsetChannel();

    void setChannel(const utility::string_t& value);

    /// <summary>
    /// Rendered content and channel/platform flags for the template.
    /// </summary>
    std::map<utility::string_t, utility::string_t>& getContent();
    bool contentIsSet() const;
    void unsetContent();

    void setContent(const std::map<utility::string_t, utility::string_t>& value);


protected:
    utility::string_t m_Id;
    bool m_IdIsSet;
    utility::string_t m_Name;
    bool m_NameIsSet;
    utility::datetime m_Created_at;
    bool m_Created_atIsSet;
    utility::datetime m_Updated_at;
    bool m_Updated_atIsSet;
    utility::string_t m_Channel;
    bool m_ChannelIsSet;
    std::map<utility::string_t, utility::string_t> m_Content;
    bool m_ContentIsSet;
};


}
}
}
}

#endif /* COM_ONESIGNAL_CLIENT_MODEL_TemplateResource_H_ */
