/**
 * OneSignal
 * A powerful way to send personalized messages at scale and build effective customer engagement strategies. Learn more at onesignal.com
 *
 * The version of the OpenAPI document: 5.3.0
 * Contact: devrel@onesignal.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.0.0-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TemplatesListResponse.h
 *
 * 
 */

#ifndef COM_ONESIGNAL_CLIENT_MODEL_TemplatesListResponse_H_
#define COM_ONESIGNAL_CLIENT_MODEL_TemplatesListResponse_H_


#include "CppRestOneSignalAPIClient/ModelBase.h"

#include "CppRestOneSignalAPIClient/model/TemplateResource.h"
#include <vector>

namespace com {
namespace onesignal {
namespace client {
namespace model {

class TemplateResource;

/// <summary>
/// 
/// </summary>
class  TemplatesListResponse
    : public ModelBase
{
public:
    TemplatesListResponse();
    virtual ~TemplatesListResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// TemplatesListResponse members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<TemplateResource>>& getTemplates();
    bool templatesIsSet() const;
    void unsetTemplates();

    void setTemplates(const std::vector<std::shared_ptr<TemplateResource>>& value);


protected:
    std::vector<std::shared_ptr<TemplateResource>> m_Templates;
    bool m_TemplatesIsSet;
};


}
}
}
}

#endif /* COM_ONESIGNAL_CLIENT_MODEL_TemplatesListResponse_H_ */
